module.exports = {
    MODE: "tdm",
    TEAMS: 4,
    TDM_END: 17,
    LABYRINTH_START: 20,
    LABYRINTH_END: 51,
    LABYRINTH_WIDTH: 43,
    LABYRINTH_HEIGHT: 21,

    LABYRINTH_INTERCONNECT_RATE_X: 30,
    LABYRINTH_INTERCONNECT_RATE_Y: 40,
    LABYRINTH_STREAK_RATE: 50,
    LABYRINTH_STREAK_SHIFT_RATE: 40,
    
    INK_EROSION_STRENGTH: 100,
    INK_EROSION_DROPOFF: 1.1,
    INK_EROSION_MINIMUM_STRENGTH: 10,
};