module.exports = {
    MODE: "tdm",
    TEAMS: 4,
    TDM_END: 17,
    UNDERGROUND_START: 20,
    UNDERGROUND_END: 51,
    UNDERGROUND_WIDTH: 43,
    UNDERGROUND_HEIGHT: 25,

    UNDERGROUND_INTERCONNECT_RATE: 40,
    UNDERGROUND_CHANNEL_SIZE_CHANGE_RATE: 70,
    UNDERGROUND_CHANNEL_ISLAND_RATE: 25,
    
    INK_EROSION_STRENGTH: 100,
    INK_EROSION_DROPOFF: 1.1,
    INK_EROSION_MINIMUM_STRENGTH: 10,
};
