module.exports = {
    MODE: "tdm",
    TEAMS: 4,
    TDM_END: 17,
    UNDERGROUND_START: 20,
    UNDERGROUND_END: 51,
    UNDERGROUND_WIDTH: 43,
    UNDERGROUND_HEIGHT: 21,

    UNDERGROUND_INTERCONNECT_RATE_X: 25,
    UNDERGROUND_INTERCONNECT_RATE_Y: 40,
    UNDERGROUND_STREAK_RATE: 50,
    UNDERGROUND_STREAK_SHIFT_RATE: 35,
    
    INK_EROSION_STRENGTH: 100,
    INK_EROSION_DROPOFF: 1.1,
    INK_EROSION_MINIMUM_STRENGTH: 10,
};